version: '3.5'

services:
  influx1:
    image: influxdb:2.0
    container_name: influx1
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ordix
      - DOCKER_INFLUXDB_INIT_PASSWORD=ordix123
      - DOCKER_INFLUXDB_INIT_ORG=ORDIX_AG
      - DOCKER_INFLUXDB_INIT_BUCKET=TestBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=b8cVNwJf16kmSR_gKR-og891kiZ1lvLIpmJCszJSh5G6mrSB7dQusSKSVTAikvn5tGl3IUhkgpAj3RdjmLqZDQ==
    volumes:
      - /var/lib/influxdb/data:/var/lib/influxdb2
      - /var/lib/influxdb/config:/etc/influxdb2

  grafana:
    image: grafana/grafana:7.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./datasrc.yml:/etc/grafana/provisioning/datasources/influx-datasrc.yml:ro
      - ./dashboards:/var/lib/grafana/dashboards
      - ./dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml:ro
      - ./grafana.ini:/etc/grafana/grafana.ini:ro